# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7644be897d4160327134853e421139cfed2b1381cb87e5948f9ac8fe67e8330f60b593ea279c683fc8c2e16cec00a99ac018af13f6780ab530f507a005546637

test:
  secret_key_base: 878a655c72ed21898e8dee2e3c37399a77c351b5acf512736bea461febde2fac0ada8b9442f2c97829300f0907be6a04706962a44df92004db05b74de8576ad0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
